name: Setup Project
description: Setup the project for the workflow

inputs:
  bun_version:
    description: The Bun version to install
    required: false

runs:
  using: composite
  steps:
    - name: Get Bun version
      if: inputs.bun_version == null
      id: get-bun-version
      shell: bash
      run: |
        BUN_VERSION=$(cat workspaces/packages/bun-workspaces/package.json | jq -r '._bwInternal.bunVersion.build')
        echo BUN_VERSION=$BUN_VERSION >> $GITHUB_ENV
        echo "Bun version to be installed: $BUN_VERSION"

    - name: Install Bun
      if: runner.os != 'Windows'
      shell: bash
      id: install-bun
      run: |
        bun_version=${{ inputs.bun_version || env.BUN_VERSION }}
        echo "Installing Bun version: $bun_version"
        export BUN_INSTALL="$HOME/.bun"
        curl -fsSL https://bun.com/install | bash -s "bun-v$bun_version"
        echo "$HOME/.bun/bin:$PATH" >> $GITHUB_PATH

    - name: Install Bun (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        iex "& {$(irm https://bun.com/install.ps1)} -Version ${{ inputs.bun_version || env.BUN_VERSION }}"
        "$env:USERPROFILE\.bun\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        bun --version

    # This is a hack to get around Bun 1.2 not supporting negation globs in the root package.json workspaces.
    # Bun 1.2 is only used for testing bun-workspaces to verify support.
    - name: Patch workspaces for Bun 1.2.x
      if: startsWith(inputs.bun_version || env.BUN_VERSION, '1.2.')
      shell: bash
      run: |
        bun --eval '
          const packageJsonPath = "package.json";
          const packageJson = JSON.parse(await Bun.file(packageJsonPath).text());
          packageJson.workspaces.packages = [
           "workspaces/packages/*",
           "workspaces/meta",
           "workspaces/web/*",
           "workspaces/libraries/*"
          ];
          await Bun.write(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);
        '
        # If we can avoid running dependency install scripts, we should do it for security
        bun install --ignore-scripts
        bun prepare

    - name: Install Dependencies
      id: install-deps
      shell: bash
      run: |
        # If we can avoid running dependency install scripts, we should do it for security
        bun install --frozen-lockfile --ignore-scripts
        bun prepare
