import {
  type CliCommandConfig,
  type CliCommandName,
  getCliCommandConfig,
} from "@pacwich/common/cli";
import type { CliCommandContent, CliCommandInfo } from "./cliOption";

const defineCommandContent = (
  commandName: CliCommandName,
  factory: (
    optionConfig: CliCommandConfig,
  ) => Omit<CliCommandInfo, "commandName">,
): CliCommandContent => {
  const config = getCliCommandConfig(commandName);
  const content = factory(config);

  const exampleLines = content.examples.filter(
    (example) => example.trim() && !example.match(/^\s*#/),
  );

  const getMainFlag = (flags: string[]) => {
    const longFlag = flags[flags.length - 1];
    return longFlag.trim().split(" ")[0];
  };

  for (const option of Object.values(config.options)) {
    if (
      !option.deprecated &&
      !exampleLines.find((line) => line.includes(getMainFlag(option.flags)))
    ) {
      throw new Error(
        `Expected an example to include ${getMainFlag(option.flags)}`,
      );
    }
  }

  if (
    !exampleLines.find((line) => {
      // line that uses no flags
      return Object.values(config.options).every(
        (option) => !line.includes(getMainFlag(option.flags)),
      );
    })
  ) {
    throw new Error(`Expected an example to use no flags`);
  }

  return {
    commandName,
    ...config,
    ...content,
  };
};

const CLI_PROJECT_COMMANDS_CONTENT = {
  addSkills: defineCommandContent("addSkills", () => ({
    title: "Add Skills",
    description:
      "Add skill files to your project. These contain docs about Pacwich for an agent.",
    examples: [
      "# Writes to .agents/skills by default",
      `pacwich add-skills`,
      "",
      "# Claude skills location",
      `pacwich add-skills --dir=.claude/skills`,
      "",
      "# Print files to be written only",
      `pacwich add-skills --dir=./my-custom-dir --dry-run`,
    ],
  })),
  verify: defineCommandContent("verify", () => ({
    title: "Verify Project",
    description:
      'Validate your project. Potentially useful as a "prepare" root package.json script or pre-commit hook',
    examples: [
      "# Default output. Shows metadata about the project",
      `pacwich verify`,
      "",
      "# Fails the command if explicit workspace dependencies are missing in package.json",
      `pacwich verify --strict`,
      "",
      "# Scope verification of missing dependencies to specific workspaces",
      `pacwich verify --strict my-workspace-a "path:my-pattern/**/*"`,
      "",
      "# Output as JSON",
      `pacwich verify --json`,
      "",
      "# Output as formatted JSON",
      `pacwich verify --json --pretty`,
    ],
  })),
  listWorkspaces: defineCommandContent("listWorkspaces", () => ({
    title: "List Workspaces",
    description: "List workspaces in the project.",
    examples: [
      "# Default output. Shows metadata about workspaces",
      `pacwich list-workspaces`,
      "",
      "# Output only the list of workspace names",
      `pacwich list-workspaces --name-only`,
      "",
      "# Output as JSON",
      `pacwich list-workspaces --json`,
      "",
      "# Output as formatted JSON",
      `pacwich list-workspaces --json --pretty`,
      "",
      "# Filter workspaces by pattern",
      `pacwich list-workspaces my-workspace "my-name-pattern-*" "path:packages/**/*"`,
      "",
      "# Filter workspaces by pattern using the --workspace-patterns|-W option",
      `pacwich list-workspaces --workspace-patterns="my-name-pattern-* path:packages/**/*"`,
    ],
  })),
  listScripts: defineCommandContent("listScripts", () => ({
    title: "List Scripts",
    description: "List all scripts available with their workspaces",
    examples: [
      "# Default output. Shows metadata about scripts found in all workspaces",
      `pacwich list-scripts`,
      "",
      "# Output only the list of script names",
      `pacwich list-scripts --name-only`,
      "",
      "# Output as JSON",
      `pacwich list-scripts --json`,
      "",
      "# Output as formatted JSON",
      `pacwich list-scripts --json --pretty`,
    ],
  })),
  workspaceInfo: defineCommandContent("workspaceInfo", () => ({
    title: "Workspace Info",
    description: "Show metadata about a workspace",
    examples: [
      "# Default output. Shows metadata about a workspace",
      `pacwich workspace-info my-workspace`,
      "",
      "# Output as JSON",
      `pacwich workspace-info my-workspace --json`,
      "",
      "# Output as formatted JSON",
      `pacwich workspace-info my-workspace --json --pretty`,
    ],
  })),
  scriptInfo: defineCommandContent("scriptInfo", () => ({
    title: "Script Info",
    description: "Show metadata about a script",
    examples: [
      "# Default output. Shows metadata about a script",
      `pacwich script-info my-script`,
      "",
      "# Output only the list of workspaces that have the script",
      `pacwich script-info my-script --workspaces-only`,
      "",
      "# Output as JSON",
      `pacwich script-info my-script --json`,
      "",
      "# Output as formatted JSON",
      `pacwich script-info my-script --json --pretty`,
    ],
  })),
  listTags: defineCommandContent("listTags", () => ({
    title: "List Tags",
    description:
      "List all tags available with their workspaces. Tags are defined in a workspace's configuration file.",
    descriptionLinks: {
      tags: "/config/workspace#tags",
      "configuration file": "/config/workspace",
    },
    examples: [
      "# Default output. Shows metadata about tags found in all workspaces",
      "# Tags are defined in a workspace's configuration file",
      `pacwich list-tags`,
      "",
      "# Output only the list of tag names",
      `pacwich list-tags --name-only`,
      "",
      "# Output as JSON",
      `pacwich list-tags --json`,
      "",
      "# Output as formatted JSON",
      `pacwich list-tags --json --pretty`,
    ],
  })),
  tagInfo: defineCommandContent("tagInfo", () => ({
    title: "Tag Info",
    description:
      "Show metadata about a tag. Tags are defined in a workspace's configuration file.",
    descriptionLinks: {
      tag: "/config/workspace#tags",
      "configuration file": "/config/workspace",
    },
    examples: [
      "# Default output. Shows metadata about a tag",
      `pacwich tag-info my-tag`,
      "",
      "# Output as JSON",
      `pacwich tag-info my-tag --json`,
      "",
      "# Output as formatted JSON",
      `pacwich tag-info my-tag --json --pretty`,
    ],
  })),
  runScript: defineCommandContent("runScript", () => ({
    title: "Run Script",
    description:
      'Run a script in all workspaces that have it in their "scripts" field in their respective package.json, or run an inline script.',
    examples: [
      '# Run my-script for all workspaces with it in their package.json "scripts" field',
      `pacwich run my-script`,
      "",
      "# Run a script for a specific workspace",
      `pacwich run my-script my-workspace`,
      "",
      "# Run a script for multiple workspaces",
      `pacwich run my-script my-workspace-a my-workspace-b`,
      "",
      "# Run a script for workspaces using alias",
      `pacwich run my-script my-alias`,
      "",
      "# Run a script for workspaces using wildcard that matches the workspace name",
      `pacwich run my-script "my-workspace-*"`,
      "",
      "# Run a script for workspaces using matching specifiers",
      `pacwich run my-script "alias:my-alias-*" "path:packages/**/*"`,
      "",
      "# Run a script for workspaces using the --workspace-patterns|-W option",
      `pacwich run my-script --workspace-patterns="my-workspace-* my-workspace-b"`,
      "",
      "# Run a script for workspaces using the --script|-S option",
      `pacwich run "my-workspace-*" my-workspace-b --script=my-script`,
      "",
      "# A workspace's script will wait until any workspaces it depends on have completed",
      `pacwich run my-script --dep-order`,
      "",
      "# Continue running scripts even if a dependency fails",
      `pacwich run my-script --dep-order --ignore-dep-failure`,
      "",
      "# Scripts run in parallel by default",
      `pacwich run my-script --parallel=false # Run in series`,
      "",
      `pacwich run my-script --parallel=auto # Default, number of available logical CPUs`,
      "",
      "# Run a script in parallel with a max of 2 concurrent scripts",
      `pacwich run my-script --parallel=2`,
      "",
      "# Run a script in parallel with a max of 50% of the available CPUs",
      `pacwich run my-script --parallel=50%`,
      "",
      "# Run a script in parallel with no concurrency limit (use with caution)",
      `pacwich run my-script --parallel=unbounded`,
      "",
      "# Use the grouped output style (default when on a TTY)",
      `pacwich run my-script --output-style=grouped`,
      "",
      "# Set the max preview lines for script output in grouped output style",
      `pacwich run my-script --output-style=grouped --grouped-lines=auto`,
      `pacwich run my-script --output-style=grouped --grouped-lines=10`,
      "",
      "# Use simple script output with workspace prefixes (default when not on a TTY)",
      `pacwich run my-script --output-style=prefixed`,
      "",
      "# Use the plain output style (no workspace prefixes)",
      `pacwich run my-script --output-style=plain`,
      "",
      "# Silence all output of the run command",
      `pacwich --log-level=silent run my-script --output-style=none`,
      "",
      "# Run an inline command from each workspace's directory",
      `pacwich run "echo 'this is my inline script for <workspaceName>'" --inline`,
      "",
      "# By default, the system shell (sh in POSIX systems, cmd in Windows) is used",
      "# You can also use the Bun shell if Bun is available, which is",
      "# a cross-platform bash-like shell.",
      `pacwich run "echo 'this is my Bun shell script'" --inline --shell=bun`,
      "",
      "# Set a name for an inline command",
      `pacwich run "echo 'inline script'" --inline --inline-name=my-name`,
      "",
      "# Append args to each script call",
      `pacwich run my-script --args="--my args"`,
      "",
      "# Append args to each script call using the -- terminator",
      `pacwich run my-script -- --my-arg --another-arg`,
      "",
      "# Use the workspace name in args",
      `pacwich run my-script --args="--my --arg=<workspaceName>"`,
      "",
      "# Output results to a JSON file",
      `pacwich run my-script --json-outfile=results.json`,
    ],
  })),
  listAffected: defineCommandContent("listAffected", () => ({
    title: "List Affected",
    description: "List all workspaces that are affected by a change",
    examples: [
      "# Default output. Shows metadata about workspaces affected",
      "# by a change against the default git base (main when not configured)",
      `pacwich list-affected`,
      "# Alias for list-affected",
      "pacwich ls-affected",
      "",
      "# Outputs reasons for affected workspaces",
      `pacwich ls-affected --explain`,
      "",
      "# More detailed output about every changed file and dependency",
      `pacwich ls-affected --explain --detailed`,
      "",
      "# Output as JSON",
      `pacwich ls-affected --json --pretty`,
      "",
      "# See affected workspaces for a specific script's inputs",
      "pacwich ls-affected --script=my-script",
      "",
      "# Configure the base or head git refs for comparison (branch, commit, tag, etc.)",
      `pacwich ls-affected --base=my-branch-a --head=my-branch-b`,
      "",
      "# Specify changed files instead of using git (paths/dirs/globs, '!' to exclude)",
      "# Separate by whitespace, using backslashes to escape spaces if needed",
      `pacwich ls-affected --files="packages/a/src/index.ts packages/b/src/index.ts"`,
      "",
      "# Ignore specific git changes that are considered by default",
      `pacwich ls-affected --ignore-untracked`,
      `pacwich ls-affected --ignore-unstaged`,
      `pacwich ls-affected --ignore-staged`,
      "# Ignores staged, unstaged, and untracked changes",
      `pacwich ls-affected --ignore-uncommitted`,
      "",
      "# Ignore changes to workspace dependencies",
      `pacwich ls-affected --ignore-workspace-deps`,
      "",
      "# Ignore changes to external dependencies (e.g. npm packages)",
      `pacwich ls-affected --ignore-external-deps`,
      "",
    ],
  })),
  runAffected: defineCommandContent("runAffected", () => ({
    title: "Run Affected",
    description: "Run a script across the workspaces affected by a change",
    examples: [
      "# Run a script for all workspaces affected by a change",
      "# using the default git base (main when not configured)",
      `pacwich run-affected my-script`,
      "",
      "# Script can be a positional arg or an option",
      "pacwich run-affected --script=my-script",
      "",
      "# Takes most options as list-affected",
      "",
      "# Configure the base or head git refs for comparison",
      `pacwich run-affected my-script --base=my-branch-a --head=my-branch-b`,
      "",
      "# Specify changed files instead of using git (paths/globs, '!' to exclude)",
      "# Separate by whitespace, using backslashes to escape spaces if needed",
      `pacwich run-affected my-script \\
  --files="packages/a/src/index.ts packages/b/src/index.ts"`,
      "",
      "# Ignore specific git changes that are considered by default",
      `pacwich run-affected my-script --ignore-untracked`,
      `pacwich run-affected my-script --ignore-unstaged`,
      `pacwich run-affected my-script --ignore-staged`,
      "# Ignores staged, unstaged, and untracked changes",
      `pacwich run-affected my-script --ignore-uncommitted`,
      "",
      "# Ignore changes to workspace dependencies",
      `pacwich run-affected my-script --ignore-workspace-deps`,
      "",
      "# Ignore changes to external dependencies (e.g. npm packages)",
      `pacwich run-affected my-script --ignore-external-deps`,
      "",
      "# Other than specifying workspaces, takes all options as run-script",
      'pacwich run-affected "echo my-inline-script" \\',
      "  --parallel=false \\",
      "  --output-style=grouped \\",
      "  --grouped-lines=10 \\",
      "  --inline \\",
      "  --inline-name=my-inline-script \\",
      "  --shell=system \\",
      "  --dep-order \\",
      "  --ignore-dep-failure \\",
      "  --args='--my-arg --another-arg=<workspaceName>' \\",
      "  --json-outfile=results.json",
      "",
    ],
  })),
  runInteractive: defineCommandContent("runInteractive", () => ({
    title: "Run Interactive",
    description:
      "Run a single script in a single workspace with stdio inherited, so the script can read user input",
    examples: [
      "# Run a script interactively in a single workspace (resolved by name or",
      "# alias). stdio is inherited so the script can read user input, and the",
      "# script's own exit code is surfaced as pacwich's.",
      "pacwich run-interactive my-script -W my-workspace",
      "",
      "# The short alias `ri` works too",
      "pacwich ri my-script -W my-workspace",
      "",
      "# The workspace can also be passed as the second positional argument",
      "pacwich run-interactive my-script my-workspace",
      "",
      "# The script can be a positional arg or the --script option, and the",
      "# workspace likewise via the second positional or the --workspace option",
      "pacwich run-interactive --script=my-script --workspace=my-workspace",
      "",
      "# Forward args to the script with --args or after --",
      "pacwich run-interactive my-script -W my-workspace --args='--watch'",
      "pacwich run-interactive my-script -W my-workspace -- --watch",
      "",
      "# Run an inline command instead of a named script",
      'pacwich run-interactive "echo my-inline-script" \\',
      "  --workspace=my-workspace \\",
      "  --inline \\",
      "  --inline-name=my-inline-script \\",
      "  --shell=system",
      "",
    ],
  })),
  mcpServer: defineCommandContent("mcpServer", () => ({
    title: "MCP Server",
    description:
      "Start the pacwich MCP (Model Context Protocol) server over stdio. Set this up with your tooling of choice.",
    examples: ["pacwich mcp-server"],
  })),
  doctor: defineCommandContent("doctor", () => ({
    title: "Doctor",
    description: "Print diagnostic information for bug reports etc.",
    examples: [
      "pacwich doctor",
      "pacwich doctor --json --pretty # Output as formatted JSON",
    ],
  })),
} as const satisfies Record<CliCommandName, CliCommandContent>;

export const getCliCommandContent = (commandName: CliCommandName) =>
  CLI_PROJECT_COMMANDS_CONTENT[commandName];

export const getCliCommandsContent = () =>
  Object.values(CLI_PROJECT_COMMANDS_CONTENT);
