import fs from "fs";
import path from "path";
import {
  DOC_SLICES,
  renderAgentsOverviewPointer,
  renderAgentsTopicBacklink,
  renderVersionStamp,
  type DocSliceSourceName,
} from "@pacwich/common/docs";
import { PACWICH_VERSION } from "@pacwich/common/version";
import {
  createAgentDocs,
  type AgentDocFileName,
} from "@pacwich/meta/util/agentDocs";

const VAR_NAMES: Record<AgentDocFileName, string> = {
  overview: "DOC_OVERVIEW",
  concepts: "DOC_CONCEPTS",
  cliExamples: "DOC_CLI",
  apiExamples: "DOC_API",
  config: "DOC_CONFIG",
  development: "DOC_DEVELOPMENT",
};

// The `agents/` split filenames + navigation footers come from the shared
// doc-slice registry (`@pacwich/common/docs`), so this build channel stays in
// sync with the MCP resources and skills. Dev docs have no slice and are
// excluded from the public split. The combined `AGENTS.md` gets no footers.
const SLICE_BY_SOURCE = new Map(
  DOC_SLICES.map((slice) => [slice.sourceName, slice]),
);

const escapeForTemplateLiteral = (content: string): string =>
  content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

if (import.meta.main) {
  const { logger, contents, combinedContent } = await createAgentDocs({
    scriptName: "pacwich:Public Agent Docs",
    includeDevDocs: false,
  });

  const constants = Object.entries(contents).map(([name, content]) => {
    return `export const ${VAR_NAMES[name as AgentDocFileName]} = \`${escapeForTemplateLiteral(content)}\`;`;
  });

  const moduleOutDir = path.resolve(
    __dirname,
    "../src/internal/generated/aiDocs",
  );

  fs.mkdirSync(moduleOutDir, { recursive: true });

  const moduleContent = [
    "// This file is generated by scripts/createPublicAgentDocs.ts. Do not edit manually.",
    "",
    ...constants,
    "",
  ].join("\n");

  const modulePath = path.join(moduleOutDir, "docs.ts");
  logger.info(`Writing ${path.relative(process.cwd(), modulePath)}...`);
  fs.writeFileSync(modulePath, moduleContent);

  const versionStamp = renderVersionStamp(PACWICH_VERSION);

  const agentsMdPath = path.join(process.cwd(), "AGENTS.md");
  logger.info(`Writing ${path.relative(process.cwd(), agentsMdPath)}...`);
  fs.writeFileSync(
    agentsMdPath,
    `
<!-- pacwich (npm package) agent documentation begin -->
${combinedContent}
${versionStamp}
<!-- pacwich (npm package) agent documentation end -->
`.trim(),
  );

  const agentsDir = path.join(process.cwd(), "agents");
  fs.mkdirSync(agentsDir, { recursive: true });
  for (const [name, content] of Object.entries(contents)) {
    const slice = SLICE_BY_SOURCE.get(name as DocSliceSourceName);
    if (!slice) continue;
    const footer =
      slice.role === "entry"
        ? renderAgentsOverviewPointer()
        : renderAgentsTopicBacklink();
    const splitPath = path.join(agentsDir, slice.agentsFileName);
    logger.info(`Writing ${path.relative(process.cwd(), splitPath)}...`);
    fs.writeFileSync(splitPath, content + footer + "\n" + versionStamp + "\n");
  }

  logger.info("Success");
}
