import {
  DOC_SLICES,
  renderSkillSeeAlso,
  type DocSlice,
  type DocSliceKey,
} from "@pacwich/common/docs";
import { PACWICH_VERSION } from "@pacwich/common/version";

export interface GeneratedSkillFile {
  /** The skill name (also its directory under `.claude/skills/`). */
  skillName: string;
  /** Path relative to the skills directory, e.g. `pacwich-cli/SKILL.md`. */
  relPath: string;
  /** Full `SKILL.md` contents (frontmatter + body + see-also + stamp). */
  contents: string;
}

export interface GenerateSkillsOptions {
  /** Slice key -> doc content. Injected (not imported) to keep this pure. */
  contentByKey: Record<DocSliceKey, string>;
  /** Override which slices to generate (defaults to all public slices). */
  slices?: readonly DocSlice[];
}

const createYamlString = (value: string): string =>
  `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

const renderFrontmatter = (slice: DocSlice): string =>
  [
    "---",
    `name: ${slice.skillName}`,
    `description: ${createYamlString(slice.description)}`,
    `when_to_use: ${createYamlString(slice.whenToUse)}`,
    "---",
  ].join("\n");

/**
 * Build self-contained `SKILL.md` files (one per slice) from the shared doc
 * registry. Pure: no filesystem access — callers (the `add-skills` command)
 * write the returned `{ relPath, contents }` entries. Re-running `add-skills`
 * is the update path, so each file carries a version stamp.
 */
export const generateSkills = ({
  contentByKey,
  slices = DOC_SLICES,
}: GenerateSkillsOptions): GeneratedSkillFile[] =>
  slices.map((slice) => ({
    skillName: slice.skillName,
    relPath: `${slice.skillName}/SKILL.md`,
    contents:
      [
        renderFrontmatter(slice),
        "",
        contentByKey[slice.key],
        renderSkillSeeAlso(slice),
        "",
        `<!-- Generated by pacwich v${PACWICH_VERSION}. Re-run \`pacwich add-skills\` to update. -->`,
      ].join("\n") + "\n",
  }));
