/**
 * Resolves the demo project's real `pacwich.project.ts` (a factory-based
 * workspacePatternConfigs entry computing each workspace's tags/rules from
 * its path) for real, against the demo project's real structure, and writes
 * the resolved output to `demo-project/generated/workspaceConfig.ts`
 * (gitignored, regenerated here on `bun install` via this workspace's
 * `prepare` script, same convention as pacwich's own `scripts/ajv.ts`).
 *
 * The browser CLI never evaluates `.ts` configs
 * (`--disable-executable-configs`), so this is the only place
 * `pacwich.project.ts`'s factory actually runs. Runs in a real temp
 * directory on real disk, since pacwich's project loader reads from the
 * filesystem, not memfs.
 */
import fs from "fs";
import os from "os";
import path from "path";
import { createFileSystemProject } from "pacwich_local";
import {
  buildBaseFileMap,
  json,
  PROJECT_ROOT,
} from "../src/web-cli-runtime/demoProjectBase";

const DEMO_PROJECT_DIR = path.join(
  import.meta.dir,
  "../src/web-cli-runtime/demo-project",
);
const GENERATED_FILE = path.join(
  DEMO_PROJECT_DIR,
  "generated/workspaceConfig.ts",
);
const REAL_PROJECT_CONFIG_SOURCE = fs.readFileSync(
  path.join(DEMO_PROJECT_DIR, "pacwich.project.ts"),
  "utf8",
);

const escapeForTemplateLiteral = (value: string): string =>
  value
    .replaceAll("\\", "\\\\")
    .replaceAll("`", "\\`")
    .replaceAll("${", "\\${");

const writeFileMapToRealDisk = (rootDirectory: string) => {
  for (const [absolutePath, content] of Object.entries(buildBaseFileMap())) {
    const relativePath = path.relative(PROJECT_ROOT, absolutePath);
    const realPath = path.join(rootDirectory, relativePath);
    fs.mkdirSync(path.dirname(realPath), { recursive: true });
    fs.writeFileSync(realPath, content);
  }
  fs.writeFileSync(
    path.join(rootDirectory, "pacwich.project.ts"),
    REAL_PROJECT_CONFIG_SOURCE,
  );
};

/**
 * `pacwich.project.ts` imports from `"pacwich/config"`, the real published
 * name, matching what an actual user would write. This workspace depends on
 * the local build under the name `pacwich_local` to avoid clashing with the
 * published package, so a `pacwich` alias only needs to exist inside the
 * temp directory for this one real evaluation.
 */
const linkPacwichPackageName = (rootDirectory: string) => {
  const pacwichLocalPackageJson = Bun.resolveSync(
    "pacwich_local/package.json",
    import.meta.dir,
  );
  const nodeModulesDir = path.join(rootDirectory, "node_modules");
  fs.mkdirSync(nodeModulesDir, { recursive: true });
  fs.symlinkSync(
    path.dirname(pacwichLocalPackageJson),
    path.join(nodeModulesDir, "pacwich"),
    "dir",
  );
};

const main = () => {
  const tempDir = fs.mkdtempSync(
    path.join(os.tmpdir(), "pacwich-web-cli-demo-"),
  );
  try {
    writeFileMapToRealDisk(tempDir);
    linkPacwichPackageName(tempDir);

    // Executable configs are enabled here on purpose: this is a trusted
    // build-time evaluation, not the untrusted browser context the CLI
    // otherwise runs in.
    const project = createFileSystemProject({
      rootDirectory: tempDir,
      packageManager: "pnpm",
      disableExecutableConfigs: false,
    });

    const workspaceTagsAndRules: Record<
      string,
      { tags: string[]; rules: unknown }
    > = {};
    for (const workspace of project.workspaces) {
      const resolved = project.config.workspaces[workspace.name];
      workspaceTagsAndRules[workspace.path] = {
        tags: resolved.tags,
        rules: resolved.rules,
      };
    }

    const output = `// Generated by scripts/generateDemoConfig.ts. Do not edit by hand.
// Regenerate with \`bun run generate-demo-config\` (also runs on \`bun install\`).

export const PACWICH_PROJECT_TS_SOURCE = \`${escapeForTemplateLiteral(REAL_PROJECT_CONFIG_SOURCE)}\`;

export const WORKSPACE_TAGS_AND_RULES: Record<
  string,
  { tags: string[]; rules: unknown }
> = ${json(workspaceTagsAndRules)};
`;

    fs.mkdirSync(path.dirname(GENERATED_FILE), { recursive: true });
    fs.writeFileSync(GENERATED_FILE, output);
    console.log(`Wrote ${path.relative(process.cwd(), GENERATED_FILE)}`);
  } finally {
    fs.rmSync(tempDir, { recursive: true, force: true });
  }
};

main();
