import { DOC_SLICES, type DocSliceKey } from "@pacwich/common/docs";
import { PACWICH_VERSION } from "@pacwich/common/version";
import { DOC_CONTENT_BY_SLICE } from "../../../src/ai/docsContent";
import { generateSkills } from "../../../src/ai/skills/generateSkills";
import { describe, expect, test } from "../../util/testFramework";

const FAKE_CONTENT: Record<DocSliceKey, string> = {
  overview: "FAKE_OVERVIEW_BODY",
  concepts: "FAKE_CONCEPTS_BODY",
  cli: "FAKE_CLI_BODY",
  api: "FAKE_API_BODY",
  config: "FAKE_CONFIG_BODY",
};

const generate = () => generateSkills({ contentByKey: FAKE_CONTENT });

describe("generateSkills", () => {
  test("emits one self-contained SKILL.md per slice", () => {
    const files = generate();
    expect(files.length).toBe(DOC_SLICES.length);
    expect(files.map((f) => f.relPath).sort()).toEqual(
      DOC_SLICES.map((s) => `${s.skillName}/SKILL.md`).sort(),
    );
  });

  test("each file has frontmatter sourced from the registry", () => {
    const files = generate();
    for (const slice of DOC_SLICES) {
      const file = files.find((f) => f.skillName === slice.skillName)!;
      expect(file.contents.startsWith("---\n")).toBe(true);
      expect(file.contents).toContain(`name: ${slice.skillName}`);
      expect(file.contents).toContain(`description: "`);
      // description text is embedded (double-quoted scalar)
      expect(file.contents).toContain(slice.description);
      expect(file.contents).toContain(slice.whenToUse);
    }
  });

  test("embeds the injected doc body (self-contained)", () => {
    const files = generate();
    for (const slice of DOC_SLICES) {
      const file = files.find((f) => f.skillName === slice.skillName)!;
      expect(file.contents).toContain(FAKE_CONTENT[slice.key]);
    }
  });

  test("see-also footer lists the sibling skill names", () => {
    const files = generate();
    const cli = files.find((f) => f.skillName === "pacwich-cli")!;
    expect(cli.contents).toContain("See also:");
    for (const other of DOC_SLICES.filter(
      (s) => s.skillName !== "pacwich-cli",
    )) {
      expect(cli.contents).toContain(other.skillName);
    }
    // topic slices point back to the entry slice for orientation
    expect(cli.contents).toContain("pacwich-overview skill");
  });

  test("the entry (overview) skill carries the 'start here' trigger and no backlink", () => {
    const overview = generate().find(
      (f) => f.skillName === "pacwich-overview",
    )!;
    expect(overview.contents).toContain("Start here for orientation");
    expect(overview.contents).not.toContain("For orientation, see");
  });

  test("stamps the pacwich version for re-run/update traceability", () => {
    const files = generate();
    for (const file of files) {
      expect(file.contents).toContain(
        "Generated by pacwich v" + PACWICH_VERSION,
      );
      expect(file.contents).toContain("pacwich add-skills");
    }
  });

  test("real DOC_CONTENT_BY_SLICE produces non-empty bodies for every slice", () => {
    const files = generateSkills({
      contentByKey: DOC_CONTENT_BY_SLICE,
    });
    for (const slice of DOC_SLICES) {
      const file = files.find((f) => f.skillName === slice.skillName)!;
      expect(file.contents.length).toBeGreaterThan(slice.description.length);
    }
  });
});
