import path from "path";
import { renderVersionStamp } from "@pacwich/common/docs";
import { PACWICH_VERSION } from "@pacwich/common/version";
import { createAgentDocs } from "../util/agentDocs";

if (import.meta.main) {
  const { logger, combinedContent } = await createAgentDocs({
    scriptName: "AGENTS.md",
    includeDevDocs: true,
  });

  logger.info("Writing to AGENTS.md");
  await Bun.write(
    path.resolve(process.env.PACWICH_PROJECT_PATH as string, "AGENTS.md"),
    "<!-- Generated by createAgentsMd.ts -->\n\n" +
      combinedContent +
      "\n" +
      renderVersionStamp(PACWICH_VERSION) +
      "\n",
  );
  logger.info("Success");
}
