import { getToolDevLockVersion } from "@pacwich/common";

if (import.meta.main) {
  const root = process.env.PACWICH_PROJECT_PATH || process.cwd();

  Bun.write(
    `${root}/mise.toml`,
    `
# Generated by script createMiseToml.ts

[tools]
node = '${getToolDevLockVersion("node")}'
bun = '${getToolDevLockVersion("bun")}'
pnpm = '${getToolDevLockVersion("pnpm")}'
`.trim() + "\n",
  );
}
