name: On Main Branch Update

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml
  runtime_matrix:
    name: Runtime Matrix
    uses: ./.github/workflows/runtime_matrix.yml
  pm_matrix:
    name: Package Manager Matrix
    uses: ./.github/workflows/pm_matrix.yml
