name: Test Given Bun version and OS

on:
  workflow_call:
    inputs:
      bun_version:
        description: The Bun version to test
        required: true
        type: string
        default: 1.3.10
      os:
        description: The OS to test
        required: true
        type: string
        default: ubuntu

  workflow_dispatch:
    inputs:
      bun_version:
        description: The Bun version to test
        required: true
        type: string
        default: 1.3.10
      os:
        description: The OS to test
        required: true
        type: choice
        options:
          - ubuntu
          - windows
          - macos
        default: ubuntu
      os_version:
        description: The OS version to test
        required: false
        type: string
        default: latest

jobs:
  run_tests:
    name: "Test Against Build: Bun ${{ inputs.bun_version }} on ${{ inputs.os }}"
    runs-on: ${{ inputs.os }}-${{ inputs.os_version || 'latest' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup
        with:
          bun_version: ${{ inputs.bun_version }}

      - name: Run Tests Against Build
        run: bun bw:build:test
