name: Test Given Versions

on:
  workflow_dispatch:
    inputs:
      test_runtime:
        required: true
        type: string
        default: node
      os:
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      bun-version:
        required: true
        type: string
        default: "1.3"
      node-version:
        required: true
        type: string
        default: "26"
      pnpm-version:
        required: true
        type: string
        default: "11"
      test_args:
        required: false
        type: string
        default: ""
  workflow_call:
    inputs:
      test_runtime:
        required: true
        type: string
        default: node
      os:
        required: true
        type: string
      bun-version:
        required: true
        type: string
      node-version:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string
      test_args:
        required: false
        type: string
        default: ""

permissions:
  contents: read

jobs:
  test_given_versions:
    name: Test Build - ${{ inputs.test_runtime }} (bun ${{ inputs.bun-version }}, node ${{ inputs.node-version }}, pnpm ${{ inputs.pnpm-version }}, ${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/bootstrap
        with:
          bun-version: ${{ inputs.bun-version }}
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}

      - name: Test Build - ${{ inputs.test_runtime }}
        shell: bash
        run: bun pw build-and-test:${{ inputs.test_runtime }} -- ${{ inputs.test_args }}
