# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Validate Code

on:
  workflow_call:
  workflow_dispatch:

jobs:
  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Format Check
        id: format-check
        run: bun format-check

  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Type Check
        id: type-check
        run: bun type-check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Lint
        id: lint
        run: bun lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Run Tests
        id: test
        run: |
          bun bw:test

  test_build:
    name: Test Against Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Project
        uses: ./.github/actions/setup
      - name: Run Tests
        id: test
        run: bun bw:build:test
